version: "3.9"
# networks:
#   default:
#     external:
#       name: k8s_net
services:
  k8s_t:
    privileged: true
    build: .
    image: azurewebapps
    container_name: kvtest
    hostname: debvmbox
    ports:
      - "8000:8000"
    tty: true
